---
title: "About"
---

## Who is this material for?

In the creation of this material we though in:

- __Danielle__, an Instructor. She develops training materials for her colleagues at the Ministry of Health. She wants to remix content to create specific training materials for public health practitioners. [Read more about Danielle](danielle-entretrainer.qmd).

## Contributing

Contributions are always welcome!

See our [Contributing guide](https://github.com/epiverse-trace/personas/blob/master/.github/CONTRIBUTING.md) for ways to get started.

Please adhere to this project's [Code of Conduct](https://github.com/epiverse-trace/.github/blob/main/CODE_OF_CONDUCT.md).

## Support

Please see our [Getting help guide](https://github.com/epiverse-trace/personas/blob/master/.github/SUPPORT.md) for support.

## Related projects

In this project, we got inspired by [Metadocencia Personas](https://www.metadocencia.org/personas/) and adapted content from [Rstudio Learner Personas](https://rstudio-education.github.io/learner-personas/).

The "Teaching Tech Together" book (G. Wilson, 2019) has a section on **Learner Personas** in [English](http://teachtogether.tech/en/index.html#s:process-personas) and [Spanish](http://teachtogether.tech/es/index.html#s:process-personas).
