---
title: "Epiverse-TRACE personas"
---

[Personas](http://teachtogether.tech/en/index.html#s:process-personas) help instructors figure out who they're trying to help and communicate an understanding to each other and to learners. Each persona has a general background, relevant prior knowledge or experience, the learner's perception of their needs, and any special considerations.

| Persona                              | In Brief                                                                                             | Epidemiology knowledge | Programming knowledge | Mathematics Knowledge |
|--------|---------------------------|-------------|-------------|-------------|
| [Lucia](lucia-outbreaks.qmd)        | A Field Epidemiologist that use R for data cleaning, plotting and report for Outbreak response.                                           | Expert                 | Competent             | Novice                |
| [Juan](juan-datero.qmd)             | A Statistician and R user in a National Health Agency with constant deployment to outbreak response.                                     | Competent              | Expert                | Competent             |
| [Patricia](patricia-discoverer.qmd) | A PhD student learning to use R and analyse Outbreak data for her collaborative project on GitHub.                                                       | Competent              | Novice                | Competent             |
| [Vania](vania-academica.qmd)          | A professor who needs ready-to-use training for her research and to pass on to students.                                                 | Expert                 | Competent             | Expert                |
| [Danielle](danielle-entretrainer.qmd)                               | A Trainer that wants to remix content to create specific training materials for public health practitioners.                              | Competent              | Expert                | Competent             |


A *novice* is someone who doesn't yet have a mental model of some field: as a result, they don't know what they don't know. Someone is *competent* if they know enough to perform routine tasks without heroic effort. Someone is an *expert* if they are able to solve common problems at a glance and harder or more unusual problems reliably.

Any learning material (lesson, case study, online training, or in-person workshop) should be designed for 1--3 specific personas. The personas above have been synthesized from ones created by Epiverse-TRACE staff for the field of infectious diseases and public health, adapting content from [Rstudio Learner Personas](https://rstudio-education.github.io/learner-personas/).