---
title: "Juan Datero"
---

1.  Juan is a data-savvy professional working at the Ministry of Health in Bolivia for almost 2 years. He is looking forward to learning how to carefully use R packages to generate modelling and statistical inference outputs.

2.  Juan is an engineer with graduate studies in Statistics. He just started a Online courses in Epidemiology where he is having training in Outbreak response. He visits package vignettes for his day-to-day work.

3.  Juan wants to reuse code with scientific rigour. He wants to suggest epidemiologist how to choose between different methods. Also, he wants to learn how Field epidemiologists interpret the outputs of modelling generated by specialised R packages. If possible, learn how to contribute to these R packages.

4.  Juan believes that time is money: every minute he spends learning something new has to pay off sooner rather than later. He is vision impaired and needs screen reader friendly material.

## Needs

- Juan needs how-to guides and glossaries to look for quick code solutions reminders and concept refreshers for outbreak analytics. 

- He also needs case-studies per disease type given his novice experience in the field. 

- He also needs to access webinars to give him a sense of where the field is going, and short, intensive online training for very specific topics.

- He would like ready-to-use tutorials he could remix teach to his colleagues at the Ministry of Health.

## Related

-   [Erika Sanitaria](erika-sanitaria.qmd): request entry material.
-   [Lucia Outbreaks](lucia-outbreaks.qmd): sometimes work together.
-   [Vania Academica](vania-academica.qmd): interested in entry material.