---
title: "Lucia Outbreaks"
---

1.  Lucia is a Field Epidemiologist working at the Ministry of Health in Paraguay for almost 4 years. She is looking forward to learning how to Make rigorous conclusions from modelling and statistical inference outputs of Outbreak analytics R packages.

2.  She is part of the Outbreaks response team after graduating from the [FETP](https://www.tephinet.org/training-programs/paraguay-field-epidemiology-training-program) (Field Epidemiology Training Program) from the global [TEPHINET](https://www.tephinet.org/training-programs) network. She doesn't think she is an excellent `R` user but spends hours using and asking about packages like `{tidyverse}`, `{ggplot2}`, and `{rmarkdown}` for data cleaning, plotting and reporting.

3.  She wants to learn how to interpret the statistical and mathematical outputs generated by infectious disease modelling R packages. For her, this is key to inform stakeholders and the general public.

4.  Lucia is a single mother; the one evening a week she spends practicing R is the only out-of-work time she’s able to take away from family responsibilities.

## Needs

- Lucia needs more time than a webinar to learn how to use new outbreak analytics R packages. 

- She needs tutorials with refreshers of applied statistics and mathematics concepts. 

- She also needs clear guidelines for the interpretation of Outbreak analytics package outputs. 

- She also needs case-studies per disease type to identify how to translate her field experience intro practice.

## Related

-   [Erika Sanitaria](erika-sanitaria.qmd): new to programming.
-   [Juan Datero](juan-datero.qmd): sometimes work together.
