---
title: "Patricia Discoverer"
---

1.  Patricia is a PhD student in Infectious Disease Epidemiology. She works with a team of data analysts (quantitative scientists and research software engineers). She is looking forward to learning how to work in Open Science projects, and also how to contribute to them.

2.  She did a Master in Epidemiology with a focus on Modelling and the Dynamics of Infectious Diseases. She is learning to do exploratory data analysis with R. She works with code at least half of her time, mainly using R for data cleaning, visualization, and generating automated reports. She is familiar with the Rstudio Graphical Interface.

3.  She wants to learn how to access and contribute to code projects that already work with Git as a version control system. She also wants to learn to start a new project on her own, and include better coding practices as soon as possible.

4.  She is not familiar with the terminal window. She never used commands to perform a particular task on her computer.

## Needs

- Patricia needs to translate theory to practice with R. 

- She needs workshops (as an opportunity to meet people) and self-paced lessons (so that she can learn new things on her own). 

- She has a complete set of cheatsheets taped up on her wall, but usually checks Stack Overflow before looking at reference manuals.

## Related

-   [Vania Academica](vania-academica.qmd)
-   [Pepe Openmanager](pepe-openmanager.qmd)
