---
title: "All Epiverse-TRACE personas"
---

| Persona                              | In Brief                                                                                                                                 | Epidemiology knowledge | Programming knowledge | Mathematics Knowledge |
|--------|-----------------------------|-------------|-------------|-------------|
| [Erika](erika-sanitaria.html)        | A Field Epidemiologist in a National Health Agency that wants to switch from Excel to R for data cleaning, make plots and create reports | Expert                 | Novice                | Novice                |
| [Lucia](lucia-outbreaks.html)        | A Field Epidemiologist that use R for data cleaning, plotting and report for Outbreak response                                           | Expert                 | Competent             | Novice                |
| [Juan](juan-datero.html)             | A Statistician and R user in a National Health Agency with constant deployment to outbreak response.                                     | Competent              | Expert                | Competent             |
| [Patricia](patricia-discoverer.html) | A PhD student learning to use R and analyse Outbreak data for her research project                                                       | Competent              | Novice                | Competent             |
| [Anya](anya-academica.html)          | A professor who needs ready-to-use training for her research and to pass on to students.                                                 | Expert                 | Competent             | Expert                |
| Toshi                                | A systems admin in a National Health Agency who has to support data analysts.                                                            | Competent              | Expert                | Novice                |
| Joselyn                              | An ex-Field epidemiologist that now leads an Outbreak response team in a National Health Agency                                          | Expert                 | Novice                | Competent             |
| Eduardo                              | An ex-Field epidemiologist with PhD research training that now leads an Outbreak analytics team                                          | Expert                 | Competent             | Competent             |
| Celina                               | A post-doc and fluent R user who needs to keep up-to-date with the latest package developments                                           | Competent              | Competent             | Competent             |
| [Yanni](yanni-githuber.html)         | An epidemiologist working with data analysts that wants to contribute to the team Open Science projects on GitHub                        | Competent              | Novice                | Competent             |
| Larry                                | A professor who is a long-life user of a different tool than R                                                                           | Expert                 | Novice                | Expert                |
| Daniel                               | A Trainer that wants to remix content to create specific training materials for public health practitioners                              | Competent              | Expert                | Competent             |
| [Pepe](pepe-openmanager.html)        | A Project Manager that wants to provide feedback to Open Science projects hosted on GitHub                                               | Competent              | Novice                | Novice                |
